---
# tasks file for /home/cisco/Documents/ndfclab/ansible/roles/setup-vpc

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [setup-vpc]                       +"
      - "----------------------------------------------------------------"

- name: Query for vPC interface between leaf1 and leaf2
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric.name }}"
    state: query
    config: "{{ interface.vpc }}"
  register: query_result

# Use flag variable 'setup_vpc' to track if we need to setup vpc.
# If it's already setup we can skip it
- ansible.builtin.set_fact:
    setup_vpc: False
- ansible.builtin.set_fact:
    setup_vpc: True
  when: query_result.response | length == 0

- name: Setup VPC Peer If Not Already Setup
  block:
    - name: Include Tasks To Create VPC Peer Between Leaf1 and Leaf2
      ansible.builtin.include_tasks: setup_vpc_peer.yml
  when: setup_vpc