
---
# This Ansible Playbook is used to Reset The Fabric

- name: Reset All Fabrics on NDFC
  hosts: ndfc
  gather_facts: false

  tasks:
    - name: Remove switch devices from NDFC fabric {{ fabric.name }}
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ fabric.name }}"
        state: deleted
      ignore_errors: yes

    - name: Delete fabric {{ fabric.name }} from NDFC
      cisco.dcnm.dcnm_rest:
        method: DELETE
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric.name }}"
      ignore_errors: yes

    - name: Remove switch devices from NDFC fabric {{ fabric_external.name }}
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ fabric_external.name }}"
        state: deleted
      ignore_errors: yes

    - name: Delete fabric {{ fabric_external.name }} from NDFC
      cisco.dcnm.dcnm_rest:
        method: DELETE
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external.name }}"
      ignore_errors: yes
