
---
# This playbook is used to test that Ansible can connect to NDFC and query the Fabric

- name: Ensure Ansible and NDFC are configured properly
  hosts: ndfc
  gather_facts: false

  tasks:
    - name: Query NDFC fabric {{ fabric.name }}
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ fabric.name }}"
        state: query
      register: data

    - debug: msg="Fabric Device Name - {{ data.response[0].logicalName }}"
    - debug: msg="Fabric Device Name - {{ data.response[1].logicalName }}"
    - debug: msg="Fabric Device Name - {{ data.response[2].logicalName }}"

