---
vrfs:
  - vrf_name: &refvrf_devnet vrf_devnet
    vrf_id: 150001
    vlan_id: 2000
    attach: []
    attach_group: all_leaf
  # -----------------------------------------------
  # Insert the new VRF vrf_app1 below into the file
  # -----------------------------------------------
  - vrf_name: &refvrf_app1 vrf_app1
    vrf_id: 50001
    vlan_id: 2010
    attach: []
    attach_group: all_leaf
networks:
  - net_name: network_devnet1
    vrf_name: *refvrf_devnet
    net_id: 130001
    vlan_id: 2301
    vlan_name: network_devnet1_vlan2301
    gw_ip_subnet: "192.168.11.1/24"
    attach: []
    attach_group: esxi
  - net_name: network_devnet2
    vrf_name: *refvrf_devnet
    net_id: 130002
    vlan_id: 2302
    vlan_name: network_devnet2_vlan2302
    gw_ip_subnet: "192.168.12.1/24"
    attach_group: esxi
  # ------------------------------------------------------------------------
  # Insert the new Networks network_web and network_app below into the file
  # ------------------------------------------------------------------------
  - net_name: network_web
    vrf_name: *refvrf_app1
    net_id: 30001
    vlan_id: 2311
    vlan_name: network_web_vlan2311
    gw_ip_subnet: "10.1.1.1/24"
    attach: []
    attach_group: esxi
  - net_name: network_app
    vrf_name: *refvrf_app1
    net_id: 30002
    vlan_id: 2312
    vlan_name: network_web_vlan2312
    gw_ip_subnet: "10.1.2.1/24"
    attach: []
    attach_group: esxi
