---

# Add later in lab
- name: Add switches to {{ fabric_external.name }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_external.name }}"
    state: merged
    config: "{{ fabric_external.inventory }}"

- name: save config of fabric {{ fabric_external.name }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external.name }}/config-save"

- name: re-deploy inventory {{ fabric_external.name }}
  cisco.dcnm.dcnm_rest:
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external.name }}/config-deploy?forceShowRun=false"
    method: POST