---
# tasks file for /home/cisco/Documents/ndfclab/ansible/roles/add-inventory


- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [add-inventory]                   +"
      - "----------------------------------------------------------------"


# Add Later in the lab
- name: Include Tasks To Query For POAP Enabled Switches
  ansible.builtin.include_tasks: query_poap.yml
  when: fabric.enable_poap

- name: Include Tasks to Add Devices to Local Fabric
  ansible.builtin.include_tasks: add_fabric.yml

# Add later in lab
- name: Include Tasks to Add Devices to External Fabric
  ansible.builtin.include_tasks: add_fabric_external.yml