---
# tasks file for /home/cisco/Documents/ndfclab/ansible/roles/manage-interfaces

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [manage-interfaces]               +"
      - "----------------------------------------------------------------"

- name: Include Tasks To Manage vPC Interfaces
  ansible.builtin.include_tasks: vpc_interfaces.yml

- name: Include Tasks To Manage Host Facing Interfaces
  ansible.builtin.include_tasks: host_interfaces.yml