---

# ADD Later in Lab
- ansible.builtin.set_fact:
    create_fabric_ext: True

# ADD Later in Lab
- ansible.builtin.set_fact:
    create_fabric_ext: False
  when: item.fabricName == fabric_external.name
  loop: "{{ result.response.DATA }}"
  loop_control:
    label: "{{ item.fabricName }}"

# ADD Later in Lab
- ansible.builtin.debug:
    msg: "Fabric {{ fabric_external.name }} Already Exists"
  when: not create_fabric_ext

# ADD Later in Lab
- name: Create External Fabric on NDFC
  vars:
    payload:
        BGP_AS: "{{ fabric_external.asn }}"
        IS_READ_ONLY: false
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external.name }}/External_Fabric"
    json_data: "{{ payload| to_json }}"
  when: create_fabric_ext
