---
# tasks file for /home/cisco/Documents/ndfclab/ansible/roles/create-fabric


- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [create-fabric]                   +"
      - "----------------------------------------------------------------"

- name: Get Fabric List
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: result

- name: Include Tasks To Create Local Fabric
  ansible.builtin.include_tasks: local_fabric.yml

# Add Later in Lab
- name: Include Tasks To Create External Fabric
  ansible.builtin.include_tasks: external_fabric.yml

# Add Later in Lab
- name: Include Tasks To Enable POAP For Local Fabric
  ansible.builtin.include_tasks: enable_poap.yml