---
# ------------------------
# CREATE NETWORKS SECTION
# ------------------------

- name: update attachments of network
  set_fact:
    update_list: "{{ update_list + update }}"
  loop: "{{ networks }}"
  loop_control:
    label: "{{ item.net_name }}"
    index_var: i
  vars:
    update_list: []
    update:
      - path: networks[{{ i }}].attach
        value: "{{ attach_group[item.attach_group] }}"

- name: update network config
  ansible.utils.update_fact:
    updates: "{{ update_list }}"
  register: updated_network

- name: current network config
  debug:
    msg: "{{ item }}"
  loop: "{{ updated_network.networks }}"
  loop_control:
    label: "{{ item.net_name }}"

- name: create networks
  cisco.dcnm.dcnm_network:
    fabric: "{{ fabric.name }}"
    config: "{{ updated_network.networks }}"