---
# tasks file for /home/cisco/Documents/ndfclab/ansible/roles/add-overlay

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [add-overlay]                     +"
      - "----------------------------------------------------------------"

- name: Include Tasks To Add Overlay VRFs
  ansible.builtin.include_tasks: add_vrfs.yml

# Add Later in Lab
- name: Include Tasks To Re-Sync Fabric After Adding VRF LITE
  ansible.builtin.include_tasks: resync_fabric.yml

- name: Include Tasks To Add Overlay Networks
  ansible.builtin.include_tasks: add_networks.yml