
---
vrf_attach_group:
  all_leaf:
    - ip_address: 10.15.27.12
    - ip_address: 10.15.27.13
    # Add later in lab
    - ip_address: 10.15.27.14
      vrf_lite:
        - peer_vrf: vrf_devnet # optional
          interface: Ethernet1/1 # mandatory
          ipv4_addr: 10.31.0.1/30 # optional
          neighbor_ipv4: 10.31.0.2 # optional
          dot1q: 2 # dot1q can be got from dcnm/optional
attach_group:
  esxi:
    - ip_address: 10.15.27.12
      ports:
        - Port-channel10
    - ip_address: 10.15.27.13
      ports:
        - Port-channel10
